//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pump_house.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gardener
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int Area { get; set; }
        public int Month { get; set; }
        public decimal Bill { get; set; }
    }
}
